/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "ylnrsykmtaicelssaqbd"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlsbnJzeWttdGFpY2Vsc3NhcWJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwMTA2NDEsImV4cCI6MjA3MzU4NjY0MX0.5kuEdO5hnvMkTKvLK8ooLZs83Hc4sAEo5OU-TKIrj-A"